
services:
  cookbook-app:
    container_name: cookbook-app
    build: ./cookbook-app
    ports:
      - "5173:5173"
    env_file:
      - ./cookbook-app/.env
    volumes:
      - ./cookbook-app:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 5173
   # environment:
     # - CHOKIDAR_USEPOLLING=true
     # - CHOKIDAR_INTERVAL=1000

  cookbook-api:
    container_name: cookbook-api
    build: ./cookbook-api
    # Nessuna porta esposta esternamente
    env_file:
      - cookbook-api/.env
    volumes:
      - ./cookbook-api:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - mongo
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000

  mongo:
    container_name: cookbook-mongo
    image: mongo:latest
    volumes:
      - ./data/mongodb:/data/db

